CHANGELOG.md
package.json

v1.1.10 と同一の内容で v1.1.11にバージョンアップします。

bump to version1.1.11

---

CHANGELOG.md
build/buildParts.js
package.json

* https://github.com/akashic-games/engine-files/pull/8 と同様のビルドファイル修正を行いました。
* また、依存akashicモジュールの更新も行いました。

ビルドスクリプトを修正する対応と依存モジュールの更新

---

CHANGELOG.md
package.json

akashic-engine@3.0.0-beta.18 に追従します。自明につきセルフマージします。

make v3.0.0-beta.4

---

CHANGELOG.md
package.json

make v3.0.0-beta.5

---

CHANGELOG.md
package.json

version 2.1.41

---

CHANGELOG.md
build/updateInnerModules.js
index.d.ts
index.js
package.json

use @akashic/pdi-types

---

build/updateChangelog.js
package.json

* CHANGELOGに現バージョンの依存モジュールを書き込むスクリプトを追加しました。

add script to update CHANGELOG (v3)

---

build/updateChangelog.js
package.json

* CHANGELOGに現バージョンの依存モジュールを書き込むスクリプトを追加しました。

add script to update CHANGELOG (v2)

---

build/updateChangelog.js
package.json

* CHANGELOGに現バージョンの依存モジュールを書き込むスクリプトを追加しました。

add script to update CHANGELOG (v1)

---

.travis.yml
CHANGELOG.md
package.json

* @akashic/akashic-engine: 3.0.0-beta.36
* @akashic/game-driver: 2.0.0-beta.11
* @akashic/pdi-types: 1.1.0
* @akashic/pdi-browser: 2.0.0-beta.10
* @akashic/pdi-common-impl: 0.0.4
* @akashic/playlog-client: 7.0.42

Update internal modules

---

CHANGELOG.md
build/updateInnerModules.js
package.json

* モジュール更新スクリプトでタグ指定してモジュールをインストールできるように修正
* モジュール更新スクリプトを用いてplaylog-clientを最新バージョンに更新

モジュール更新スクリプト改修とモジュール(playlog-client)の更新

---

CHANGELOG.md
build/updateInnerModules.js
package.json

[@akashic/game-configuration](https://github.com/akashic-games/game-configuration) を依存に追加します。

add @akashic/game-configuration

---

CHANGELOG.md
package.json
src/akashicEngine.js
src/engineFiles.canvas.js
src/engineFiles.js

- AudioAssetなどの後方互換対応
- playlog-client 更新
セルフマージします。

v3.0.12; AudioAssetなどの後方互換対応

---

CHANGELOG.md
package.json

掲題どおり。過渡期のため一時的に game-driver のバージョンを戻します。
セルフマージします。

v3.0.13; use game-driver@2.0.3

---

.github/workflows/test.yml
README.md
build/updateExpected.ts
package-lock.json
package.json
tests/fixtures/acobench/scenario.json
tests/helpers/runReftest.ts
tests/helpers/runScenario.ts
tests/helpers/scenario.ts
tests/reftest.spec.ts
tsconfig.json

reftest の正解画像データ (#35) を更新するスクリプトを追加します。

reftest の正解画像データの更新スクリプトを追加

---

package-lock.json
package.json

掲題どおり。現時点で経緯が明らかではありませんが、あきらかに optionalDependencies と重複 (バージョンも違う) していておかしいので取り急ぎ削除します。
自明につきセルフマージします。

remove duplicated playlog-client from dependencies

---

CHANGELOG.md
package-lock.json
package.json
src/engineFiles.js

engine-files の依存関係が不足している影響で `require()` できない問題を修正します。

fix: 依存関係の修正 (v1)

---

CHANGELOG.md
package.json
src/engineFiles.canvas.js
src/engineFiles.js

engine-files の依存関係が不足している影響で `require()` できない問題を修正します。

fix: 依存関係の修正 (v2)

---

CHANGELOG.md
package-lock.json
package.json

engine-files の依存関係が不足している影響で `require()` できない問題を修正します。

fix: 依存関係の修正 (v3)

---

.github/workflows/release.yml
.github/workflows/update_internal_modules.yml
README.md
package-lock.json
package.json

* リリースワークフローを追加
* 内部モジュールの更新ワークフローを追加
内部モジュールの更新ワークフローのサンプル PullRequest は [こちら](https://github.com/yu-ogi/engine-files/pull/3) から参照できます。

feat: リリースワークフロー、内部モジュールの更新ワークフローを追加

---

.github/workflows/release.yml

GitHub Releases の作成後に成果物をアップロードするように修正します。

feat: GitHub Releases に成果物をアップロードするように

---

.github/workflows/update_internal_modules.yml

engine-files の孫依存までに複数のバージョンの akashic-engine が入り込んでいる際に中断するようにします。

fix: 重複モジュールをチェックするように

---

.github/workflows/update_internal_modules.yml

engine-files の孫依存までに複数のバージョンの akashic-engine が入り込んでいる際に中断するようにします。
#63 にてレビュー済みのためセルフマージします。

fix: 重複モジュールをチェックするように (v2-main)

---

.github/workflows/update_internal_modules.yml

engine-files の孫依存までに複数のバージョンの akashic-engine が入り込んでいる際に中断するようにします。
#63 にてレビュー済みのためセルフマージします。

fix: 重複モジュールをチェックするように (v1-main)

---

CHANGELOG.md
package-lock.json
package.json

`v1.2.0` と同し内容で publish しなおします。
自明のためセルフマージします。

Bump version v1.2.1

---

.github/workflows/update_internal_modules.yml
.npmrc
package-lock.json
package.json

バージョンを明示的に固定し、更新時に反映するため、いくつかの孫依存を追加します。
セルフマージします。

fix: 間接的な依存をdependenciesに追加

---

.github/workflows/update_internal_modules.yml

dispatch_workflow の inputs 上限 (10 個) に引っかかったので暫定的にまとめます。
セルフマージします。

fix: reduce too may inputs of update_internal_module.yml

---

.github/workflows/release.yml
CHANGELOG.md
package-lock.json
package.json

`@akashic/engine-files@3.3.0-beta.0` をリリースします。
* @akashic/akashic-engine: 3.5.0-beta.1
* @akashic/amflow: 3.1.0
* @akashic/amflow-util: 1.1.0
* @akashic/game-configuration: 1.4.0
* @akashic/game-driver: 2.8.0-beta.0
* @akashic/pdi-browser: 2.3.0-beta.0
* @akashic/pdi-common-impl: 1.0.0
* @akashic/pdi-types: 1.4.0-beta.1
* @akashic/playlog: 3.1.0
* @akashic/trigger: 1.0.1
* @akashic/headless-akashic: ^3.0.1

Release 3.3.0-beta.0

---

CHANGELOG.md
package-lock.json
package.json

`@akashic/engine-files@3.3.0-beta.1` をリリースします。
* @akashic/akashic-engine: 3.5.0-beta.2
* @akashic/amflow: 3.1.0
* @akashic/amflow-util: 1.1.0
* @akashic/game-configuration: 1.4.0
* @akashic/game-driver: 2.8.0-beta.1
* @akashic/pdi-browser: 2.3.0-beta.0
* @akashic/pdi-common-impl: 1.0.0
* @akashic/pdi-types: 1.4.0-beta.1
* @akashic/playlog: 3.1.0
* @akashic/trigger: 1.0.1
* @akashic/headless-akashic: ^3.0.1

Release 3.3.0-beta.1

---

.github/workflows/release.yml
CHANGELOG.md
package-lock.json
package.json

Release 3.3.0

---

.github/workflows/release.yml
CHANGELOG.md
package-lock.json
package.json

Update to v3.4.0

---

CHANGELOG.md
package-lock.json
package.json

掲題どおり。
v3.4.0 に不具合 (music の再生がループしない) 問題が見つかったため、対処までの暫定対応として内容を v3.3.4 相当に戻します。
変更点自明につきセルフマージします。

Update to v3.5.0 (revert to v3.3.4 contents)

---

CHANGELOG.md
package-lock.json
package.json

* reftest実行時にengine-files側でcanvasを持っておくことが必要になったので、`"devDependencies"`にcanvasを追加

add canvas to devDependencies

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update_internal_modules.yml

Update CI node version

---

package-lock.json
package.json

V1 の package.json の akashic-pdi のバージョン指定を `^` に変更します
自明のためセルフマージとします。

Change version specification of akachic-pdi

---

package-lock.json
package.json

V2 の package.json の akashic-pdi のバージョン指定を `^` に変更します
自明のためセルフマージとします。

Change version specification of akashic-pdi

---

CHANGELOG.md
package-lock.json
package.json

#142 の v1 向け対応です。
経緯と背景は #142 を参照してください。
セルフマージします。

chore: bump v1.4.0

---

.github/workflows/release.yml
.github/workflows/test.yml

actions で macOS が[エラー](https://github.com/akashic-games/engine-files/actions/runs/8996011402/job/24711912437)となったため修正。その他、修正。
- npm@7 の指定を削除
- test.yml の node の対象バージョンを 18.x, 20.x へ修正
- macos-latest が m1 チップの仮想マシンとなり、canvas のビルドで必要なライブラリがなくエラーとなった。そのため、macOS のみ brew で必要ライブラリをインストールするように修正。

Fix actions

---

CHANGELOG.md
package-lock.json
package.json

Revert "Update to 3.9.3"
